### ISSUE TITLE
Include meaningful x-wasm-custom

### ISSUE THREAD

**Issue by jcchavezs** [intel/modsecurity-wasm-filter#8]
Right now we include "x-wasm-custom: FOO" which I believe comes from example but I wonder if we really need to add this header and/or what would be an interesting value over `FOO`. Otherwise we just remove it.

https://github.com/intel/modsecurity-wasm-filter/blob/10114c1ef10ccf4aeb6aab1dc59b6036e0a957b4/wasmplugin/envoy-wasm-modsecurity.cc#L251

**Comment by bryanwux** [comment]
I agree we don't really need this custom `x-wasm-custom` header, or is there anything else you suggest to be placed here?

**Comment by jcchavezs** [comment]
I don't really have anything interesting we could add it in here. I think
anything modsec related would be leaking information about modsec rules.
Let's remove it for now.

søn. 8. mai 2022, 09:18 skrev Bryan Wu ***@***.***>:
